import { Loader2, QrCode, ShieldAlert } from 'lucide-react'
import { Button } from '@/components/ui/button'

interface TFADisabledCardProps {
  onStartSetup: () => void
  isGenerating: boolean
}

export const TFADisabledCard = ({ onStartSetup, isGenerating }: TFADisabledCardProps) => {
  return (
    <div className="space-y-4">
      <div className="flex items-center gap-4 p-4 border rounded-xl">
        <div className="p-2 rounded-lg">
          <ShieldAlert className="size-6" />
        </div>
        <div>
          <h4 className="font-semibold text-sm">2FA is Not Configured</h4>
          <p className="text-xs text-muted-foreground leading-relaxed">
            Add an extra layer of security to your account. When enabled, you'll need to enter a
            6-digit code generated by your authenticator app in addition to your password.
          </p>
        </div>
      </div>

      <Button onClick={onStartSetup} disabled={isGenerating}>
        {isGenerating ? <Loader2 className="size-4 animate-spin" /> : <QrCode className="size-4" />}
        Setup 2FA Authenticator
      </Button>
    </div>
  )
}
