/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthLayoutRouteImport } from './routes/_auth-layout'
import { Route as AppLayoutRouteImport } from './routes/_app-layout'
import { Route as AppLayoutIndexRouteImport } from './routes/_app-layout/index'
import { Route as AuthLayoutVerifyEmailRouteImport } from './routes/_auth-layout/verify-email'
import { Route as AuthLayoutVerify2faRouteImport } from './routes/_auth-layout/verify-2fa'
import { Route as AuthLayoutSignUpRouteImport } from './routes/_auth-layout/sign-up'
import { Route as AuthLayoutResetPasswordRouteImport } from './routes/_auth-layout/reset-password'
import { Route as AuthLayoutLoginRouteImport } from './routes/_auth-layout/login'
import { Route as AuthLayoutForgotPasswordRouteImport } from './routes/_auth-layout/forgot-password'
import { Route as AppLayoutSettingsRouteImport } from './routes/_app-layout/settings'

const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/_auth-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLayoutRoute = AppLayoutRouteImport.update({
  id: '/_app-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLayoutIndexRoute = AppLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AuthLayoutVerifyEmailRoute = AuthLayoutVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutVerify2faRoute = AuthLayoutVerify2faRouteImport.update({
  id: '/verify-2fa',
  path: '/verify-2fa',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutSignUpRoute = AuthLayoutSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutResetPasswordRoute = AuthLayoutResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutLoginRoute = AuthLayoutLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutForgotPasswordRoute =
  AuthLayoutForgotPasswordRouteImport.update({
    id: '/forgot-password',
    path: '/forgot-password',
    getParentRoute: () => AuthLayoutRoute,
  } as any)
const AppLayoutSettingsRoute = AppLayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/settings': typeof AppLayoutSettingsRoute
  '/forgot-password': typeof AuthLayoutForgotPasswordRoute
  '/login': typeof AuthLayoutLoginRoute
  '/reset-password': typeof AuthLayoutResetPasswordRoute
  '/sign-up': typeof AuthLayoutSignUpRoute
  '/verify-2fa': typeof AuthLayoutVerify2faRoute
  '/verify-email': typeof AuthLayoutVerifyEmailRoute
  '/': typeof AppLayoutIndexRoute
}
export interface FileRoutesByTo {
  '/settings': typeof AppLayoutSettingsRoute
  '/forgot-password': typeof AuthLayoutForgotPasswordRoute
  '/login': typeof AuthLayoutLoginRoute
  '/reset-password': typeof AuthLayoutResetPasswordRoute
  '/sign-up': typeof AuthLayoutSignUpRoute
  '/verify-2fa': typeof AuthLayoutVerify2faRoute
  '/verify-email': typeof AuthLayoutVerifyEmailRoute
  '/': typeof AppLayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app-layout': typeof AppLayoutRouteWithChildren
  '/_auth-layout': typeof AuthLayoutRouteWithChildren
  '/_app-layout/settings': typeof AppLayoutSettingsRoute
  '/_auth-layout/forgot-password': typeof AuthLayoutForgotPasswordRoute
  '/_auth-layout/login': typeof AuthLayoutLoginRoute
  '/_auth-layout/reset-password': typeof AuthLayoutResetPasswordRoute
  '/_auth-layout/sign-up': typeof AuthLayoutSignUpRoute
  '/_auth-layout/verify-2fa': typeof AuthLayoutVerify2faRoute
  '/_auth-layout/verify-email': typeof AuthLayoutVerifyEmailRoute
  '/_app-layout/': typeof AppLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/settings'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/sign-up'
    | '/verify-2fa'
    | '/verify-email'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/settings'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/sign-up'
    | '/verify-2fa'
    | '/verify-email'
    | '/'
  id:
    | '__root__'
    | '/_app-layout'
    | '/_auth-layout'
    | '/_app-layout/settings'
    | '/_auth-layout/forgot-password'
    | '/_auth-layout/login'
    | '/_auth-layout/reset-password'
    | '/_auth-layout/sign-up'
    | '/_auth-layout/verify-2fa'
    | '/_auth-layout/verify-email'
    | '/_app-layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppLayoutRoute: typeof AppLayoutRouteWithChildren
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth-layout': {
      id: '/_auth-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app-layout': {
      id: '/_app-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app-layout/': {
      id: '/_app-layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppLayoutIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_auth-layout/verify-email': {
      id: '/_auth-layout/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof AuthLayoutVerifyEmailRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth-layout/verify-2fa': {
      id: '/_auth-layout/verify-2fa'
      path: '/verify-2fa'
      fullPath: '/verify-2fa'
      preLoaderRoute: typeof AuthLayoutVerify2faRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth-layout/sign-up': {
      id: '/_auth-layout/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthLayoutSignUpRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth-layout/reset-password': {
      id: '/_auth-layout/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthLayoutResetPasswordRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth-layout/login': {
      id: '/_auth-layout/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLayoutLoginRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth-layout/forgot-password': {
      id: '/_auth-layout/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthLayoutForgotPasswordRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_app-layout/settings': {
      id: '/_app-layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppLayoutSettingsRouteImport
      parentRoute: typeof AppLayoutRoute
    }
  }
}

interface AppLayoutRouteChildren {
  AppLayoutSettingsRoute: typeof AppLayoutSettingsRoute
  AppLayoutIndexRoute: typeof AppLayoutIndexRoute
}

const AppLayoutRouteChildren: AppLayoutRouteChildren = {
  AppLayoutSettingsRoute: AppLayoutSettingsRoute,
  AppLayoutIndexRoute: AppLayoutIndexRoute,
}

const AppLayoutRouteWithChildren = AppLayoutRoute._addFileChildren(
  AppLayoutRouteChildren,
)

interface AuthLayoutRouteChildren {
  AuthLayoutForgotPasswordRoute: typeof AuthLayoutForgotPasswordRoute
  AuthLayoutLoginRoute: typeof AuthLayoutLoginRoute
  AuthLayoutResetPasswordRoute: typeof AuthLayoutResetPasswordRoute
  AuthLayoutSignUpRoute: typeof AuthLayoutSignUpRoute
  AuthLayoutVerify2faRoute: typeof AuthLayoutVerify2faRoute
  AuthLayoutVerifyEmailRoute: typeof AuthLayoutVerifyEmailRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthLayoutForgotPasswordRoute: AuthLayoutForgotPasswordRoute,
  AuthLayoutLoginRoute: AuthLayoutLoginRoute,
  AuthLayoutResetPasswordRoute: AuthLayoutResetPasswordRoute,
  AuthLayoutSignUpRoute: AuthLayoutSignUpRoute,
  AuthLayoutVerify2faRoute: AuthLayoutVerify2faRoute,
  AuthLayoutVerifyEmailRoute: AuthLayoutVerifyEmailRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppLayoutRoute: AppLayoutRouteWithChildren,
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
